# Generated by Django 3.1.6 on 2021-02-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210217_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='downvotes',
            new_name='hearts',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='upvotes',
            new_name='likes',
        ),
    ]
