# Generated by Django 3.1.6 on 2021-02-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
