# Generated by Django 3.1.6 on 2021-02-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210220_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.score'),
        ),
    ]
