# Generated by Django 3.1.6 on 2021-02-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210220_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.score'),
        ),
    ]
