# Generated by Django 3.1.6 on 2021-02-24 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210220_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ticker', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=256)),
                ('avg_buy_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('avg_sell_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_of_purchase', models.DateTimeField()),
                ('date_of_sale', models.DateTimeField(blank=True)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolio')),
            ],
        ),
    ]
