# Generated by Django 3.1.6 on 2021-02-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_investment_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date_of_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date_of_sale',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
